### ISSUE TITLE
bot is not buying throwing out of stock 

### ISSUE THREAD

**Issue by brzozex** [Pouya69/OrderBot#1]
HI, i checked with random item on Amazon, and its not going into basket when article is available and price is correct.

**Comment by Pouya69** [comment]
Sorry for late response buddy. Popular websites like Amazon and BestBuy do update their websites a lot so that bots cannot do the same thing over time. They will change the tag names etc. 

There is also a Captcha for some purchases that I have encountered that I have no solutions for it lol. Captcha is MEANT to stop bots and this is a bot :)
